# -*- coding: utf-8 -*-
"""lab5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xgd6Yjsj3FBKTzk7QgiKsX82Uc6uqzcD

# **Simulação dos exemplos do capítulo 5 pelo método de Monte Carlo**

# Exemplo 9
"""

import numpy as np
u = np.random.uniform(0,1)
n = int(input())
soma = 0
for i in range(n):
  u = np.random.uniform(0,1)
  soma = soma +(np.exp(-u**2))/n
print(soma)

"""# Exemplo 10"""

def exponencial(lam):
  u = np.random.uniform(0,1)
  x = -np.log(1-u)/lam
  return x

def gerar_bernoulli ( p ):
 u = np.random.uniform( 0 , 1 )
 if  u<= p:
  return 1
 else :
   return 0

def normal_padrao():
  Y = exponencial(1)
  u = np.random.uniform(0.1)
  B = gerar_bernoulli(0.5)
  while u >= np.exp(-(Y-1)/2):
    Y = exponencial(1)
    u = np.random.uniform(0,1)
  if B == 1:
    return Y
  else:
    return -Y
print(normal_padrao())

pn = 0
n = int(input())
for i in range(n):
  if normal_padrao() > 1:
   pn = pn+ 1
   resultado = pn/n
  else:
    resultado = pn/n
print(resultado)

"""# Exemplo 11"""

n = int(input())

contador = 0
for i in range(n):
  x = np.random.uniform(0,1)
  y = np.random.uniform(0,1)
  if x**2 + y**2<= 1:
    contador = contador + 1
    resultado = 4*(contador/n)
  else:
    resultado = 4*(contador/n)
print(resultado)

"""# Exemplo 12"""

n = int(input())
soma1 = 0
soma2 = 0
for i in range(n):
  x = np.random.uniform(0,1)
  soma1 = soma1 + x
resultado1 = soma1/n
print(resultado1)

for i in range(n):
  y = np.random.uniform(0,1)
  soma2 = soma2 +((y-resultado1)**2)
resultado2 = soma2/(n-1)
print(resultado2)

"""# Exemplo 13"""

n = int(input())
soma = 0
for i in range(n):
  x = np.random.uniform(0,1)
  y = np.random.uniform(0,1)
  soma = soma +np.exp(-x**2-y**2)
resultado = soma/n
print(resultado)

"""# Exemplo 14"""

n = int(input())
soma = 0
def exponencial(lam):
  u = np.random.uniform(0,1)
  x = -np.log(1-u)/lam
  return x

for i in range(n):
  soma = soma + np.exp(-exponencial(1))
resultado = soma/n
print(resultado)

"""# Exemplo 15"""

n = int(input())
soma = 0
def exponencial(lam):
  u = np.random.uniform(0,1)
  x = -np.log(1-u)/lam
  return x

for i in range(n):
  soma = soma + (1/(1+exponencial(1)))
resultado = soma/n
print(resultado)

"""# Exemplo 16"""

n = int(input())
soma = 0
def exponencial(lam):
  u = np.random.uniform(0,1)
  x = -np.log(1-u)/lam
  return x

for i in range(n):
  soma = soma + (np.sin(exponencial(1))/(1+exponencial(1)*np.exp(-exponencial(1))))
resultado = soma/n
print(resultado)