# -*- coding: utf-8 -*-
"""lab9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v6ZjqH04VTrxrvF16YyfRuwSyVwZCJxM

# Exercício 1
"""

import numpy as np
import matplotlib.pyplot as plt
# Z = 1/(1+u²), Y = u²,muy = 1/12+ 1/4 = 1/3
N = 1000
Us = np.random.uniform(size=1000)
Xs = 1/(1+Us**2)
Ys = Us**2
muy = 1/3

Cs = np.cov(Xs,Ys)
c = -Cs[0,1]/Cs[1,1]

Zs = Xs + c*(Ys-muy)

print(Cs[0,0])
var_z = np.var(Zs)
print(var_z)

Xs.mean()*4,Zs.mean()*4

plt.hist(Zs*4)
plt.hist(Xs*4)

"""# Exercício 2"""

# Z = X +c*(Y - muy), Y ~U(0,1)
n = int(input())
Us = np.random.uniform(size=1000)
Xs = np.exp(Us)
Cs = np.cov(Xs,Us)
c = -Cs[0,1]/Cs[1,1]
Zs = Xs + c*(Us-0.5)


print(Cs[0,0])
var_z = np.var(Zs)
print(var_z)
print(Zs)
print(Xs)

"""# Exercício 3"""

uniformes = []
for i in range(10000):
  u = np.random.uniform(0,1)
  uniformes.append(u)
print(uniformes)
exponenciais = []
lam = 1
for u in uniformes:
  x = -np.log(1-u)/lam
  exponenciais.append(x)
print(exponenciais)

indicadoras = []
contador = 0
for i in exponenciais:
    if  i > 1:
      contador += 1
indicadoras.append(contador/10000)
media = np.mean(indicadoras)
print(indicadoras)

#Por variável controle Z = (X + (Y-1))
uniformes = []
for i in range(10000):
  u = np.random.uniform(0,1)
  uniformes.append(u)
print(uniformes)
exponenciais = []
lam = 1
for u in uniformes:
  x = -np.log(1-u)/lam
  exponenciais.append(x)
print(exponenciais)

indicadoras = []
contador = 0
for i in exponenciais:
    if  i > 1:
      contador += 1
    indicadoras.append(contador/10000)
print(indicadoras)
print(np.mean(indicadoras))
array_exponenciais = np.array(exponenciais)
array_indicadoras = np.array(indicadoras)
Cs = np.cov(array_exponenciais,array_indicadoras)
c = -Cs[0,1]/Cs[1,1]

Zs = array_indicadoras + c*(array_exponenciais-1)

print(Cs[0,0])
var_z = np.var(Zs)
print(var_z)

plt.hist(indicadoras)
plt.hist(Zs)