# -*- coding: utf-8 -*-
"""lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ukVA7GcwrK2-MaCNZjHIAfRTsb8nKBpa

# Exercício 1
"""

import numpy as np
import matplotlib.pyplot as plt
def exponencial(lam):
  u = np.random.uniform(0,1)
  x = -np.log(1-u)/lam
  return x

def density_of_exponencial(x, lam=1):
  return lam*np.exp(-lam*x)

amostra = [exponencial(1) for _ in range(100000)]
x = np.linspace(0, 5, 1000)
plt.plot(x, density_of_exponencial(x))
plt.hist(amostra, density=True)
plt.show()
# Com lambda grande
amostra1 = [exponencial(2) for _ in range(1000)]
plt.hist(amostra1)
plt.show()

amostra2 = np.random.exponential(scale=1/(2), size=1000)
plt.hist(amostra2)
plt.show()
#Aqui podemos perceber que os histogramas ficam bem parecidos quando nosso lambda é grande

#Quando lambda  é pequeno os histogramas não ficam muito parecidos
amostra3 = [exponencial(0.2) for _ in range(1000)]
print(amostra3)

plt.hist(amostra3)
plt.show()
amostra3 = np.random.exponential(scale=1/(0.2), size=1000)
print(amostra2)
plt.hist(amostra2)
plt.show()
#Quando lambda pequeno é  os histogramas não ficam muito parecido,tanto quanto com lambda grande

"""# Exercício 2"""

import math
#Versão recursiva geométrica
def exponencial_geometrica(lam,n):
  p = lam
  u = np.random.uniform(0,1)
  x = math.floor((np.log(1-u)/np.log(1-p))) + 1
  return x/n

amostra1 = [exponencial_geometrica(0.4,50) for _ in range(100000)]
plt.hist(amostra1)
plt.show()

amostra2 = [exponencial_geometrica(0.4,500) for _ in range(100000)]

plt.hist(amostra2)
plt.show()

amostra3 = [exponencial_geometrica(0.4,5000) for _ in range(100000)]
plt.hist(amostra3)
plt.show()

def exponencial(lam):
  u = np.random.uniform(0,1)
  x = -np.log(1-u)/lam
  return x

def density_of_exponencial(x, lam=0.4):
  return lam*np.exp(-lam*x)

amostra = [exponencial(1) for _ in range(100000)]
y = np.linspace(0, 5, 1000)
plt.plot(y, density_of_exponencial(y))
plt.hist(amostra, density=True)
plt.show()

"""
# Exercício 3"""

def poisson_via_exp(mu):
  sum = 0
  contador = 0
  while sum <= 1:
    l = exponencial(mu)
    sum = sum + l
    contador = contador + 1
  return contador - 1

amostra = [poisson_via_exp(4) for _ in range(10000)]
print(amostra)
plt.hist(amostra)
plt.show()

media = np.mean(amostra)Exemplo 9
variancia = np.var(amostra)
print(media)
print(variancia)

amostra_np = np.random.poisson(4,10000)
plt.hist(amostra_np)
plt.show()

# O número teórico é E[X] = 4 e Var[x] = 4
media = np.mean(amostra)
variancia = np.var(amostra)
print(media)
print(variancia)
# Assim podemos perceber que os resultados estão bem próximos