# -*- coding: utf-8 -*-
"""lab0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LIl013Rq_BwHAsl-azHqRNB2Ean_xYQb
"""

#lab0

#Passo1
distribuiçoes = {"Normal": {"params": {"loc": 0, "scale": 1}, "dados": None, "estatisticas": None},
    "Exponencial": {"params": {"scale": 2}, "dados": None, "estatisticas": None},
    "Uniforme": {"params": {"low": -1, "high": 1}, "dados": None, "estatisticas": None}
}

#Passo2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.random.normal(loc=0, scale=1, size= 1000)
amostra_normal = np.random.normal(loc=0, scale=1,size=1000)
#fazendo por loop
#amostra_normal = []
#for i in range(1000):
     # i = np.random.normalnormal(loc=0, scale=1, size= 1000)
     # i.append(amostra_normal)



np.random.exponential(scale= 2,size= 1000)
amostra_exponencial = np.random.exponential(scale= 2,size= 1000)

np.random.uniform(low = -1, high = 1,size = 100)
amostra_uniforme = np.random.uniform(low = -1, high = 1,size = 1000)



distribuiçoes['Normal']['dados'] = amostra_normal

distribuiçoes['Exponencial']['dados'] = amostra_exponencial

distribuiçoes['Uniforme']['dados'] = amostra_uniforme

mean_normal = np.mean(amostra_normal)
med_normal = np.median(amostra_normal)
std_normal = np.std(amostra_normal)
var_normal = np.var(amostra_normal)

distribuiçoes['Normal']['estatisticas'] = {"média":mean_normal, "med_normal":med_normal,"variância":var_normal,"desvio padrão":std_normal}


print(distribuiçoes)

mean_exponencial = np.mean(amostra_exponencial)
med_exponencial = np.median(amostra_exponencial)
std_exponencial = np.std(amostra_exponencial)
var_exponencial = np.var(amostra_exponencial)

print(amostra_exponencial)

distribuiçoes['Exponencial']['estatisticas'] = {"média":mean_exponencial, "med_normal":med_normal,"variância":var_normal,"desvio padrão":std_normal}

mean_uniforme = np.mean(amostra_uniforme)
med_uniforme = np.median(amostra_uniforme)
std_uniforme = np.std(amostra_uniforme)
var_uniforme = np.var(amostra_uniforme)

distribuiçoes['Uniforme']['estatisticas'] = {"média":mean_exponencial, "med_normal":med_normal,"variância":var_normal,"desvio padrão":std_normal}

plt.hist(amostra_normal, bins=57)

plt.hist(amostra_exponencial, bins=57)

plt.hist(amostra_uniforme, bins=57)

distribuiçoes["Binomial"] = {"params": {"n":50, "p":0.5}, "dados": None, "estatisticas": None}
amostra_binomial = np.random.binomial(n=50,p=0.5,size = 1000)

distribuiçoes["Poisson"] = {"params": {"lam":3}, "dados": None, "estatisticas": None}
amostra_poisson = np.random.poisson(lam=3,size = 1000)

min_normal = np.min(amostra_normal)
max_normal = np.max(amostra_normal)
quart_normal1 = np.quantile(amostra_normal, 0.25)
quar_normal2 = np.quantile(amostra_normal,0.75)

distribuiçoes['Normal']['estatisticas'] = {"mínimo":min_normal, "máximo":max_normal,"Primeiro quartil":quart_normal1,"Segundo quartil":med_normal,"Terceiro quartil": quar_normal2}

min_exponencial = np.min(amostra_exponencial)
max_exponencial = np.max(amostra_exponencial)
quart_exponencial1 = np.quantile(amostra_exponencial, 0.25)
quar_exponencial2 = np.quantile(amostra_exponencial,0.75)

distribuiçoes['Exponencial']['estatisticas'] = {"mínimo":min_exponencial, "máximo":max_exponencial,"Primeiro quartil":quart_exponencial1,"Segundo quartil":med_exponencial,"Terceiro quartil": quar_exponencial2}

min_uniforme = np.min(amostra_uniforme)
max_uniforme = np.max(amostra_uniforme)
quart_uniforme1 = np.quantile(amostra_uniforme, 0.25)
quar_uniforme2 = np.quantile(amostra_uniforme,0.75)

distribuiçoes['Uniforme']['estatisticas'] = {"mínimo":min_uniforme, "máximo":max_uniforme,"Primeiro quartil":quart_uniforme1,"Segundo quartil":med_uniforme,"Terceiro quartil": quar_uniforme2}

mean_poisson = np.mean(amostra_poisson)
med_poisson = np.median(amostra_poisson)
std_poisson = np.std(amostra_poisson)
var_poisson = np.var(amostra_poisson)

distribuiçoes['Poisson']['estatisticas'] = {"média":mean_poisson, "med_normal":med_poisson,"variância":var_poisson,"desvio padrão":std_poisson}

min_poisson = np.min(amostra_poisson)
max_poisson = np.max(amostra_poisson)
quart_poisson1 = np.quantile(amostra_poisson, 0.25)
quar_poisson2 = np.quantile(amostra_poisson,0.75)

distribuiçoes['Poisson']['estatisticas'] = {"mínimo":min_poisson, "máximo":max_poisson,"Primeiro quartil":quart_poisson1,"Segundo quartil":med_poisson,"Terceiro quartil": quar_poisson2}

mean_binomial = np.mean(amostra_binomial)
med_binomial = np.median(amostra_binomial)
std_binomial = np.std(amostra_binomial)
var_binomial = np.var(amostra_binomial)

distribuiçoes['Binomial']['estatisticas'] = {"média":mean_binomial, "med_normal":med_binomial,"variância":var_binomial,"desvio padrão":std_binomial}

min_binomial = np.min(amostra_binomial)
max_binomial = np.max(amostra_binomial)
quart_binomial1 = np.quantile(amostra_binomial, 0.25)
quar_binomial2 = np.quantile(amostra_binomial,0.75)

distribuiçoes['Binomial']['estatisticas'] = {"mínimo":min_binomial, "máximo":max_binomial,"Primeiro quartil":quart_binomial1,"Segundo quartil":med_binomial,"Terceiro quartil": quar_binomial2}

plt.hist(amostra_normal, bins=57)
plt.hist(amostra_exponencial, bins=57)
plt.hist(amostra_uniforme,bins = 57)
plt.hist(amostra_possion,bins = 57)
plt.hist(amostra_binomial,bins = 57)

#Comparando as médias amostrais
mean_normal_pop = 0
dif_mean_normal = mean_normal_pop - mean_normal
print(dif_mean_normal)
mean_exponencial_pop = 1/2
dif_mean_exponencial = mean_exponencial_pop - mean_exponencial
print(dif_mean_exponencial)
mean_uniforme_pop = (1-(-1))/2
dif_mean_uniforme = mean_uniforme_pop - mean_uniforme
print(dif_mean_uniforme)
mean_binomial_pop = 50*0.5
dif_mean_binomial = mean_binomial_pop - mean_binomial
print(dif_mean_binomial)
mean_poisson_pop = 3
dif_mean_poisson = mean_poisson_pop - mean_poisson
print(dif_mean_poisson)