# -*- coding: utf-8 -*-
"""lab6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rZGE42c_qR913uUd51dgV9OGffw4ntH3

# Intervalo de confiança do exemplo 9
"""

import numpy as np
u = np.random.uniform(0,1)
sequencia =[]
n = int(input())
soma = 0
for i in range(n):
  u = np.random.uniform(0,1)
  sequencia.append(u)
  soma = soma +(np.exp(-u**2))/n
print(soma)
print(sequencia)
desvio_padrao = np.std(sequencia)
primeiro_numero = soma - 1.96*(desvio_padrao/np.sqrt(n))
segundo_numero = soma + 1.96*(desvio_padrao/np.sqrt(n))
print("[%.2f,%.2f]"%(primeiro_numero,segundo_numero))

"""# Intervalo de confiança do exemplo 10"""

sequencia = []
def exponencial(lam):
  u = np.random.uniform(0,1)
  x = -np.log(1-u)/lam
  return x

def gerar_bernoulli ( p ):
 u = np.random.uniform( 0 , 1 )
 if  u<= p:
  return 1
 else :
   return 0

def normal_padrao():
  Y = exponencial(1)
  u = np.random.uniform(0.1)
  B = gerar_bernoulli(0.5)
  while u >= np.exp(-(Y-1)/2):
    Y = exponencial(1)
    u = np.random.uniform(0,1)
  if B == 1:
    return Y
  else:
    return -Y
print(normal_padrao())

pn = 0
n = int(input())
for i in range(n):
  normal = normal_padrao()
  sequencia.append(normal)
  if normal_padrao() > 1:
   pn = pn+ 1
   resultado = pn/n
  else:
    resultado = pn/n
print(resultado)
desvio_padrao = np.std(sequencia)
primeiro_numero = resultado - 1.96*(desvio_padrao/np.sqrt(n))
segundo_numero = resultado + 1.96*(desvio_padrao/np.sqrt(n))
print("[%.2f,%.2f]"%(primeiro_numero,segundo_numero))

"""# Intervalo de confiança do exemplo 11"""

n = int(input())
sequencia = []
contador = 0
for i in range(n):
  x = np.random.uniform(0,1)
  y = np.random.uniform(0,1)
  sequencia.append([x,y])
  if x**2 + y**2<= 1:
    contador = contador + 1
    resultado = 4*(contador/n)
  else:
    resultado = 4*(contador/n)
print(resultado)
print(sequencia)
desvio_padrao = np.std(sequencia)
print(desvio_padrao)
primeiro_numero = soma - 1.96*(desvio_padrao/np.sqrt(n))
segundo_numero = soma + 1.96*(desvio_padrao/np.sqrt(n))
print("[%.2f,%.2f]"%(primeiro_numero,segundo_numero))

"""# Intervalo de confiança do exemplo 16"""

n = int(input())
soma = 0
sequencia = []
def exponencial(lam):
  u = np.random.uniform(0,1)
  x = -np.log(1-u)/lam
  return x

for i in range(n):
  u = exponencial(1)
  sequencia.append(u)
  soma = soma + (np.sin(u)/(u*np.exp(-u)))
resultado = soma/n
print(resultado)
print(sequencia)
desvio_padrao = np.std(sequencia)
print(desvio_padrao)
primeiro_numero = resultado - 1.96*(desvio_padrao/np.sqrt(n))
segundo_numero = resultado + 1.96*(desvio_padrao/np.sqrt(n))
print("[%.2f,%.2f]"%(primeiro_numero,segundo_numero))

"""# Exercício 2"""

for i in range(1,1000):
  n = i
def exponencial(lam):
  u = np.random.uniform(0,1)
  x = -np.log(1-u)/lam
  return x

def gerar_bernoulli ( p ):
 u = np.random.uniform( 0 , 1 )
 if  u<= p:
  return 1
 else :
   return 0

def normal_padrao():
  Y = exponencial(1)
  u = np.random.uniform(0,1)
  B = gerar_bernoulli(0.5)
  while u >= np.exp(-(Y-1)**2/2):
    Y = exponencial(1)
    u = np.random.uniform(0,1)
  if B == 1:
    return Y
  else:
    return -Y
print(normal_padrao())

sequencia_esperanca = []
sequencia_max =[]

for i in range(1,1000):
  n = i
  for _ in range(n):
    sequencia = []
    normal = normal_padrao()
    sequencia.append(normal)
  maximo = max(sequencia)
  sequencia_max.append(maximo)
  esperanca = np.mean(sequencia_max)
  sequencia_esperanca.append(esperanca)
  print(esperanca)
  print(sequencia_esperanca)

