# -*- coding: utf-8 -*-
"""lab7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-KZoDqc2pg5z1PMmsHJw-ReofXlE9ahQ

# Exercício 1
"""

import numpy as np
import matplotlib.pyplot as plt

def gerar_bernoulli ( p ):
 u = np.random.uniform( 0 , 1 )
 if  u<= p:
  return 1
 else :
   return 0
def exponencial(lam):
  u = np.random.uniform(0,1)
  x = -np.log(1-u)/lam
  return x

def normal_padrao():
  Y = exponencial(1)
  u = np.random.uniform(0.1)
  B = gerar_bernoulli(0.5)
  while u >= np.exp(-(Y-1)/2):
    Y = exponencial(1)
    u = np.random.uniform(0,1)
  if B == 1:
    return Y
  else:
    return -Y
print(normal_padrao())

def normal(mu,sigma2):
  Y = exponencial(1)
  u = np.random.uniform(0.1)
  B = gerar_bernoulli(0.5)
  sigma = np.sqrt(sigma2)
  while u >= np.exp(-(Y-1)/2):
    Y = exponencial(1)
    u = np.random.uniform(0,1)
  if B == 1:
    return (sigma*Y) + mu
  else:
    return (sigma*(-Y)) + mu

def dens_normal(x,mi):
  return np.exp(-(x-mi)**2/((np.pi*2)**0.5))

def indicadora(x,a):
  return x > a

#Primeira bolinha
n = 100000
soma = 0
for i in range(n):
  x = normal_padrao()
  soma += indicadora(x,10)
print(soma/n)

#Segunda bolinha
n = 100000
soma_2 = 0
for i in range(n):
  z = normal(10,1)
  soma_2 += indicadora(z,10)* dens_normal(z,0)/dens_normal(z,10)
print(soma_2/n)

eixo = np.linspace(-5,5,1000)
plt.plot(eixo,dens_normal(eixo,0))
plt.plot(eixo,indicadora(eixo,0))

"""Assim podemos perceber que nos 2 métodos os valores são bem próximos um do outro

# Exercício 2
"""

def funcao_g(x):
  funcao = 10*np.exp(-5*(x-5)**4)
  return funcao
eixo_2 = np.linspace(-5,10,100)
plt.plot(eixo_2,funcao_g(eixo_2))

#Pelo nosso plot escolhemos mu1 = 5
dens_normal_ut = dens_normal(5,1)

eixo_3 = np.linspace(-10,10,100)
plt.plot(eixo_3,dens_normal_ut(eixo_3,1))
plt.plot(eixo_3,normal_padrao(eixo_3,1))